list: $/shohabbos/catalog/models/slide/columns.yaml
modelClass: Shohabbos\Catalog\Models\Slide
title: Slides
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'shohabbos/catalog/slides/update/:id'
